on:
  pull_request:
    branches:
    - dev

jobs:
  build_camunda:
    name: Build camunda
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v3.10.0
      with:
        java-version: 19
        distribution: oracle
        java-package: jdk
    - name: Maven build camunda
      working-directory: engine/camunda
      run: mvn -B package --file pom.xml
